## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
#  - osx
julia:
  - 1.0
#  - nightly
notifications:
  email: false
git:
  depth: 10
#matrix:
#  allow_failures:
#  - julia: nightly

addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
            - hdf5-tools

## uncomment following lines to deploy documentation
jobs:
   include:
     - stage: Documentation
       julia: 1.0
       os: linux
       script:
#         - export JL_PKG=RegularizedLeastSquares
#         - julia -e 'using Pkg; Pkg.instantiate()' #; Pkg.develop(PackageSpec(path=pwd()))'
#         - julia --color=yes docs/make.jl
         - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
         - julia --project=docs docs/make.jl
       after_success: skip

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl

## uncomment the following lines to override the default test script
#script:
#  - xvfb-run julia --check-bounds=yes --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true); else using Pkg; Pkg.test(coverage=true); end"
#  - LD_PRELOAD=${HOME}/.julia/packages/Conda/deps/usr/lib/libz.so julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("MPIReco"); Pkg.test("MPIReco"; coverage=true)'
after_success:
#  # push coverage results to Coveralls
#  - julia -e 'using Pkg; cd(Pkg.dir("MPIReco")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
#  - julia -e 'using Pkg; cd(Pkg.dir("MPIReco")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
#  - julia -e 'using Pkg; cd(Pkg.dir("MPIReco")); ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs", "make.jl"))'
