_type = "RecoPlan{MultiPatchReconstructionAlgorithm}"
_module = "MPIReco"

[parameter]
_type = "RecoPlan{MultiPatchParameters}"
_module = "MPIReco"

    [parameter.reco]
    _type = "RecoPlan{PeriodicMotionReconstructionParameter}"
    _module = "MPIReco"

        [parameter.reco.freqFilter]
        _type = "RecoPlan{SNRThresholdFrequencyFilterParameter}"
        _module = "MPIReco"

        [parameter.reco.solverParams]
        _type = "RecoPlan{SimpleSolverParameters}"
        _module = "MPIReco"

        [parameter.reco.weightingParams]
        _module = "AbstractImageReconstruction"
        _type = "RecoPlan{ProcessResultCache}"
        maxsize = 1

            [parameter.reco.weightingParams.param]
            _module = "MPIReco"
            _type = "RecoPlan{NoWeightingParameters}"


    [parameter.pre]
    _module = "AbstractImageReconstruction"
    _type = "RecoPlan{ProcessResultCache}"

    [parameter.pre.param]
        _type = "RecoPlan{PeriodicMotionPreProcessing}"
        _module = "MPIReco"

    [parameter.post]
    _type = "RecoPlan{NoPostProcessing}"
    _module = "MPIReco"
