_module = "MPIReco"
_type = "RecoPlan{SinglePatchReconstructionAlgorithm}"

[parameter]
_module = "MPIReco"
_type = "RecoPlan{SinglePatchParameters}"

    [parameter.reco]
    _module = "MPIReco"
    _type = "RecoPlan{SinglePatchReconstructionParameter}"

        [parameter.reco.sfLoad]
        _module = "AbstractImageReconstruction"
        _type = "RecoPlan{ProcessResultCache}"

            [parameter.reco.sfLoad.param]
            _module = "MPIReco"
            _type = "RecoPlan{SparseSystemMatrixLoadingParameter}"

                [parameter.reco.sfLoad.param.freqFilter]
                _module = "MPIReco"
                _type = "RecoPlan{SNRThresholdFrequencyFilterParameter}"

                [parameter.reco.sfLoad.param.gridding]
                _module = "MPIReco"
                _type = "RecoPlan{SystemMatrixGriddingParameter}"

        [[parameter.reco._listener.sf]]
        field = "minFreq"
        _module = "AbstractImageReconstruction"
        _type = "LinkedFieldListener"
        plan = ["parameter", "reco", "sfLoad", "param", "freqFilter"]

            [parameter.reco._listener.sf.fn]
            _module = "MPIReco"
            _type = "defaultParameterMinFreq"
        [[parameter.reco._listener.sf]]
        field = "maxFreq"
        _module = "AbstractImageReconstruction"
        _type = "LinkedFieldListener"
        plan = ["parameter", "reco", "sfLoad", "param", "freqFilter"]

            [parameter.reco._listener.sf.fn]
            _module = "MPIReco"
            _type = "defaultParameterMaxFreq"
        [[parameter.reco._listener.sf]]
        field = "recChannels"
        _module = "AbstractImageReconstruction"
        _type = "LinkedFieldListener"
        plan = ["parameter", "reco", "sfLoad", "param", "freqFilter"]

            [parameter.reco._listener.sf.fn]
            _module = "MPIReco"
            _type = "defaultParameterRecChannels"

        [parameter.reco.solverParams]
        _module = "MPIReco"
        _type = "RecoPlan{ElaborateSolverParameters}"

    [parameter.pre]
    _module = "AbstractImageReconstruction"
    _type = "RecoPlan{ProcessResultCache}"

        [parameter.pre.param]
        _module = "MPIReco"
        _type = "RecoPlan{CommonPreProcessingParameters}"

    [parameter.post]
    _module = "MPIReco"
    _type = "RecoPlan{NoPostProcessing}"
