_module = "MPIReco"
_type = "RecoPlan{SinglePatchReconstructionAlgorithm}"

[parameter]
_module = "MPIReco"
_type = "RecoPlan{SinglePatchParameters}"

    [parameter.reco]
    _module = "MPIReco"
    _type = "RecoPlan{SinglePatchReconstructionParameter}"

        [parameter.reco.sfLoad]
        _module = "AbstractImageReconstruction"
        _type = "RecoPlan{ProcessResultCache}"
        maxsize = 3

            [parameter.reco.sfLoad.param]
            _module = "MPIReco"
            _type = "RecoPlan{DenseSystemMatixLoadingParameter}"

                [parameter.reco.sfLoad.param.freqFilter]
                _module = "MPIReco"
                _type = "RecoPlan{SNRThresholdFrequencyFilterParameter}"

                    [[parameter.reco.sfLoad.param.freqFilter._listener.minFreq]]
                    field = "sf"
                    _module = "AbstractImageReconstruction"
                    _type = "LinkedPropertyListener"
                    plan = ["parameter", "reco"]

                        [parameter.reco.sfLoad.param.freqFilter._listener.minFreq.fn]
                        _module = "MPIReco"
                        _type = "defaultParameterMinFreq"

                    [[parameter.reco.sfLoad.param.freqFilter._listener.maxFreq]]
                    field = "sf"
                    _module = "AbstractImageReconstruction"
                    _type = "LinkedPropertyListener"
                    plan = ["parameter", "reco"]

                        [parameter.reco.sfLoad.param.freqFilter._listener.maxFreq.fn]
                        _module = "MPIReco"
                        _type = "defaultParameterMaxFreq"

                [parameter.reco.sfLoad.param.gridding]
                _module = "MPIReco"
                _type = "RecoPlan{SystemMatrixGriddingParameter}"

                    [[parameter.reco.sfLoad.param.gridding._listener.fov]]
                    field = "sf"
                    _module = "AbstractImageReconstruction"
                    _type = "LinkedPropertyListener"
                    plan = ["parameter", "reco"]

                        [parameter.reco.sfLoad.param.gridding._listener.fov.fn]
                        _module = "MPIReco"
                        _type = "defaultParameterCalibFov"

                    [[parameter.reco.sfLoad.param.gridding._listener.center]]
                    field = "sf"
                    _module = "AbstractImageReconstruction"
                    _type = "LinkedPropertyListener"
                    plan = ["parameter", "reco"]

                        [parameter.reco.sfLoad.param.gridding._listener.center.fn]
                        _module = "MPIReco"
                        _type = "defaultParameterCalibCenter"

                    [[parameter.reco.sfLoad.param.gridding._listener.gridsize]]
                    field = "sf"
                    _module = "AbstractImageReconstruction"
                    _type = "LinkedPropertyListener"
                    plan = ["parameter", "reco"]

                        [parameter.reco.sfLoad.param.gridding._listener.gridsize.fn]
                        _module = "MPIReco"
                        _type = "defaultParameterGridSize"

        [parameter.reco.solverParams]
        _module = "MPIReco"
        _type = "RecoPlan{ElaborateSolverParameters}"

    [parameter.pre]
    _module = "AbstractImageReconstruction"
    _type = "RecoPlan{ProcessResultCache}"

        [parameter.pre.param]
        _module = "MPIReco"
        _type = "RecoPlan{CommonPreProcessingParameters}"

    [parameter.post]
    _module = "MPIReco"
    _type = "RecoPlan{NoPostProcessing}"